name: On Push
on:
  push:
    branches:
      - main

jobs:
  publish_artifacts:
    name: Release and publish
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: write
      issues: write
      pull-requests: write
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: ${{ env.node-version }}
          cache: 'npm'

      - name: Install and Build
        run: |
          npm ci
          npm run build

      - name: Publish Core Components
        run: npm publish --access public
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
          NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
